"""Re-exports default upstream base URLs from the config provider catalog."""

from config.provider_catalog import (
    ANTHROPIC_DEFAULT_BASE,
    CF_GATEWAY_V1_DEFAULT_BASE,
    DEEPSEEK_ANTHROPIC_DEFAULT_BASE,
    DEEPSEEK_DEFAULT_BASE,
    FIREWORKS_DEFAULT_BASE,
    GEMINI_DEFAULT_BASE,
    KIMI_DEFAULT_BASE,
    LLAMACPP_DEFAULT_BASE,
    LMSTUDIO_DEFAULT_BASE,
    NVIDIA_NIM_DEFAULT_BASE,
    OLLAMA_DEFAULT_BASE,
    OPENAI_DEFAULT_BASE,
    OPENROUTER_DEFAULT_BASE,
    SILICONFLOW_DEFAULT_BASE,
    ZAI_DEFAULT_BASE,
)

__all__ = (
    "ANTHROPIC_DEFAULT_BASE",
    "CF_GATEWAY_V1_DEFAULT_BASE",
    "DEEPSEEK_ANTHROPIC_DEFAULT_BASE",
    "DEEPSEEK_DEFAULT_BASE",
    "FIREWORKS_DEFAULT_BASE",
    "GEMINI_DEFAULT_BASE",
    "KIMI_DEFAULT_BASE",
    "LLAMACPP_DEFAULT_BASE",
    "LMSTUDIO_DEFAULT_BASE",
    "NVIDIA_NIM_DEFAULT_BASE",
    "OLLAMA_DEFAULT_BASE",
    "OPENAI_DEFAULT_BASE",
    "OPENROUTER_DEFAULT_BASE",
    "SILICONFLOW_DEFAULT_BASE",
    "ZAI_DEFAULT_BASE",
)
